export const GENERAL_CHATTER = [
  { message: "All units, signal 10-2 is strong. Check in by sector.", code: "10-2", channel: "SYSTEM" },
  { message: "Control, traffic is heavy on the bypass, possible delay for response.", code: "10-13", channel: "PD" },
  { message: "Weather advisory: High winds reported. All units exercise caution.", code: "10-1", channel: "SYSTEM" },
  { message: "Unit 105, what is your 10-20?", code: "10-20", channel: "PD" },
  { message: "10-20 is 5th and Main, proceeding to next sector.", code: "10-20", channel: "PD" },
  { message: "Control, 10-6 for a technical update. Stand by.", code: "10-6", channel: "SYSTEM" },
  { message: "All sectors, 10-12 in progress at central precinct.", code: "10-12", channel: "PD" },
  { message: "Unit 202, confirm 10-4 on the last transmission.", code: "10-4", channel: "PD" },
  { message: "10-36? Dispatch time check.", code: "10-36", channel: "SYSTEM" },
  { message: "Be advised, radio interference reported in the valley.", code: "10-1", channel: "SYSTEM" },
]

export const DEPT_CHATTER = {
  police: [
    { message: "Control, we have a suspect foot pursuit in the alleyway!", code: "10-33", channel: "PD" },
    { message: "10-15 suspect in custody. Requesting a 10-19 to processing.", code: "10-15", channel: "PD" },
    { message: "Running a 10-28 on a silver sedan, NJ plate Delta-Xray-4.", code: "10-28", channel: "PD" },
    { message: "10-29 check on the subject. Stand by.", code: "10-29", channel: "PD" },
    { message: "Subject is 10-99. High risk warrants confirmed.", code: "10-99", channel: "PD" },
    { message: "Unit 7, 10-41. Starting patrol shift.", code: "10-41", channel: "PD" },
    { message: "Dispatch, we are 10-23 at the scene. Establishing perimeter.", code: "10-23", channel: "PD" },
    { message: "Requesting 10-78 for a combative subject. Need backup!", code: "10-78", channel: "PD" },
    { message: "Search in progress. K-9 unit is 10-23 and deploying.", code: "10-23", channel: "PD" },
    { message: "All units, 10-31 in progress. Armed robbery at the bank.", code: "10-31", channel: "PD" },
  ],
  fire: [
    { message: "Engine 1 is 10-23. Heavy smoke showing from the alpha side.", code: "10-23", channel: "FD" },
    { message: "Truck 4 has water on the fire. Starting primary search.", code: "10-4", channel: "FD" },
    { message: "Control, we have a fully involved structure. Requesting second alarm.", code: "10-33", channel: "FD" },
    { message: "Fire Marshal is 10-19 to the station for evidence review.", code: "10-19", channel: "FD" },
    { message: "Engine 2 checking hydrants on Waasis. All functional.", code: "10-4", channel: "FD" },
    { message: "Search complete. Primary and secondary are all clear.", code: "10-4", channel: "FD" },
    { message: "Ventilation in progress on the roof. Be advised.", code: "10-4", channel: "FD" },
    { message: "Hazmat unit is 10-23. Securing the perimeter.", code: "10-23", channel: "FD" },
  ],
  ems: [
    { message: "Medic 1 is 10-23. Patient is unresponsive, starting ACLS.", code: "10-23", channel: "EMS" },
    { message: "Dispatch, we are 10-17 with one patient, returning to medical intake.", code: "10-17", channel: "EMS" },
    { message: "Ambulance 5 is 10-7 for restocking and decontamination.", code: "10-7", channel: "EMS" },
    { message: "Patient 10-22. Cancel the ER notification.", code: "10-22", channel: "EMS" },
    { message: "Medic unit is clear from handoff, 10-8 for next assignment.", code: "10-8", channel: "EMS" },
    { message: "Starting CPR. Requesting an additional medic unit for assist.", code: "10-33", channel: "EMS" },
    { message: "Vitals are stable. Proceeding with 10-17 at Code 2 speed.", code: "10-17", channel: "EMS" },
    { message: "Triage complete. Multiple green and yellow tags on scene.", code: "10-4", channel: "EMS" },
  ],
  tow: [
    { message: "Tow 1 is 10-23. Vehicle is heavily damaged, prep for flatbed.", code: "10-23", channel: "TOW" },
    { message: "Recovery unit 10-19 to impound with felony vehicle.", code: "10-19", channel: "TOW" },
    { message: "Wrecker 3 is 10-76 to the multi-vehicle crash on the bridge.", code: "10-76", channel: "TOW" },
    { message: "Roadway is 10-24. All debris cleared from the lane.", code: "10-24", channel: "TOW" },
    { message: "Tow unit is 10-8 and returning to the yard.", code: "10-8", channel: "TOW" },
    { message: "Dispatch, we have a jackknifed semi. Requesting heavy lift cert unit.", code: "10-33", channel: "TOW" },
  ],
}
