export const INCIDENT_TYPES = [
  'Active shooter',
  'ALPR checkpoint',
  'Alarm - commercial',
  'Alarm - residential',
  'Animal attack',
  'Animal complaint',
  'Animal smuggling',
  'Armed foot pursuit',
  'Armed person report',
  'Armed vehicle pursuit',
  'Arson investigation',
  'Assault in progress',
  'Attempted homicide',
  'ATM tampering',
  'Auto theft',
  'Abandoned luggage',
  'Bar fight',
  'Bicycle stolen',
  'Breaking and entering',
  'Brawl',
  'Breakdown of public bus',
  'Breakdown of vehicle',
  'Burglary alarm',
  'Burglary in basement',
  'Burglary in progress',
  'Cable theft',
  'Caller hangup',
  'Car jacking',
  'Car ran out of gas',
  'Child abduction',
  'Child locked in vehicle',
  'Child welfare check',
  'Community assistance',
  'Counterfeit goods raid',
  'Counterfeit report',
  'Credit card skimming',
  'Curfew violation',
  'Demonstration protest',
  'Demonstration against construction project',
  'Disorderly conduct',
  'Disturbance of peace',
  'Domestic disturbance',
  'Domestic dispute',
  'Domestic violence',
  'Drive by shooting',
  'Drunk driver report',
  'DUI checkpoint',
  'Drug deal',
  'Drug warrant',
  'Driving under the influence of narcotics',
  'Escort request',
  'Fight in progress',
  'Fleeing suspect',
  'Found property',
  'Fraud report',
  'Gas station robbery',
  'Graffiti complaint',
  'Harassment report',
  'High-risk warrant',
  'Hit and run',
  'Home invasion',
  'Hostage taken',
  'Homicide investigation',
  'Horse riding accident with vehicle',
  'Identity theft',
  'Illegal fishing',
  'Illegal parking',
  'Illegal street racing',
  'Illegal tapping of electricity',
  'Impaired driver report',
  'Kidnapped public official',
  'Kidnapping',
  'Keys locked in vehicle',
  'Large STPO operation',
  'Leaf vacuum out of control',
  'Loitering',
  'Lost child',
  'Mental health concern',
  'Mental health crisis',
  'Missing person',
  'Motorcycle accident',
  'Neighbor dispute',
  'Noise complaint',
  'Notebook stolen from school',
  'Obstruction of traffic',
  'Officer down',
  'Officer robbery',
  'Out of control argument',
  'Overdose',
  'Overdose report',
  'Panic button activation',
  'Parked car accident',
  'Parade escort',
  'Parole violation',
  'Peaceful demonstration (small)',
  'Person check',
  'Person with a weapon',
  'Pickpocketing',
  'Plant smuggling',
  'Possible cannabis farm',
  'Prisoner bus accident',
  'Prisoner escape',
  'Property damaged',
  'Protest monitoring',
  'Public intoxication',
  'Reported fraud',
  'Residential burglar alarm triggered',
  'Residential police raid',
  'Restaurant food theft',
  'Restraining order violation',
  'Riot',
  'Robbery',
  'Robbery in progress',
  'Road hazard',
  'Road rage incident',
  'Scooter accident',
  'Search of a vehicle',
  'Security check',
  'Serve court order',
  'Serve eviction notice',
  'Shoplifting',
  'Shots fired',
  'Shots fired at officer',
  'Shots heard',
  'Shooting',
  'Silent alarm triggered inside bank',
  'Small violent protest',
  'Stabbing',
  'Stalker',
  'Stolen credit card',
  'Stolen police car',
  'Stolen vehicle',
  'Stray animal',
  'Structure fire (police assist)',
  'Suicide concern',
  'Suspicious activity',
  'Suspicious package',
  'Suspicious person',
  'Suspicious vehicle',
  'Theft in progress',
  'Theft of property from vehicles',
  'Traffic collision',
  'Traffic collision - injuries',
  'Traffic collision - fatal',
  'Traffic control',
  'Traffic fight',
  'Traffic stop',
  'Trespassing',
  'Unresponsive person',
  'Vandalism',
  'Vehicle crash - property damage',
  'Vehicle fire',
  'Vehicle lost its load',
  'Vehicle pursuit',
  'Vehicle repossession gone wrong',
  'Vehicle rollover',
  'Warrant enforcement',
  'Warrant stabbing',
  'Welfare check',
  'Weapon brandished',
  'Wild animal attack during spring',
  'Wilderness first aid',
]

export const INCIDENT_DETENTION_OVERRIDES = {
  'Active shooter': true,
  'Armed foot pursuit': true,
  'Armed person report': true,
  'Armed vehicle pursuit': true,
  'Assault in progress': true,
  'Attempted homicide': true,
  'Car jacking': true,
  'Child abduction': true,
  'Domestic violence': true,
  'Drive by shooting': true,
  'Homicide investigation': true,
  'Kidnapping': true,
  'Robbery': true,
  'Robbery in progress': true,
  'Shots fired': true,
  'Shots fired at officer': true,
  'Shooting': true,
  'Stabbing': true,
  'Stolen vehicle': true,
  'Vehicle pursuit': true,
  'Traffic collision - fatal': true,
  'Traffic collision - injuries': true,
  'Prisoner escape': true,
  'Warrant enforcement': true,
  'Warrant stabbing': true,
  'Warrant': true,
  'DUI checkpoint': false,
  'Lost child': false,
  'Welfare check': false,
  'Noise complaint': false,
  'Road hazard': false,
  'Community assistance': false,
}
