import { INCIDENT_TYPES as POLICE_INCIDENT_TYPES } from './incidents'

export const ADDITIONAL_POLICE_INCIDENT_TYPES = [
  'Active Shooter / Mass Violence',
  'Armed Robbery in Progress',
  'Bank Robbery (Silent Alarm)',
  'Hostage Situation / Standoff',
  'Officer Needs Assistance (10-78)',
  'Suspect Foot Pursuit',
  'High-Speed Vehicle Pursuit',
  'Warrant Service (High Risk)',
  'Drug Lab / Narcotics Bust',
  'Bomb Threat / Suspicious Package',
  'Gang Activity Report',
  'Homicide Investigation',
  'Kidnapping in Progress',
  'Riot / Civil Unrest',
  'Illegal Street Racing',
  'Shots Fired Call',
  'Stabbing / Assault with Weapon',
  'Domestic Violence (Armed Subject)',
  'Burglary in Progress',
  'Grand Larceny Auto',
  'DUI / Impaired Driver (Erratic)',
  'Suspicious Person with Firearm',
  'Welfare Check (Possible DOA)',
  'Child Abduction / Amber Alert',
  'Behavioral Health Crisis (Law Assist)',
  'Missing Endangered Person Search',
  'Civil Standby / Custody Exchange',
  'Runaway Juvenile Report',
  'Domestic Disturbance (Verbal Escalation)',
  'Suspicious Package (Transit Hub)',
  'Road Rage with Weapon',
  'Burglary Alarm Verification',
  'Welfare Check (No Contact)',
  'Fraud in Progress (Bank Alert)',
  'Shoplifting Detention Assist',
  'Harassment / Stalking Repeat Caller',
  'Reckless Driver (Weather Related)',
  'Nor\'easter Evacuation Assist',
  'Causeway Closure Enforcement',
  'Coastal Access Restriction Patrol',
  'Post-Storm Curfew Enforcement',
  'Bridge Icing Traffic Control',
  'Power Outage Neighborhood Patrol',
  'Port Security Disturbance',
  'Ferry Terminal Crowd Control',
  // Legacy/compat names kept for existing logic/tests.
  'School lockdown assist',
  'Demonstration against the construction of a highway project',
]

export const CURATED_POLICE_INCIDENT_TYPES = Array.from(
  new Set([...POLICE_INCIDENT_TYPES, ...ADDITIONAL_POLICE_INCIDENT_TYPES])
)

export const FIRE_INCIDENT_TYPES = [
  // Legacy/compat names kept for existing logic/tests.
  'Structure fire',
  'Gas leak',
  'Industrial fire',
  'Structure Fire (Commercial)',
  'Structure Fire (Residential)',
  'Structure Fire (High-Rise)',
  'Industrial Plant Explosion',
  'Hazmat Leak (Toxic Gas)',
  'Chemical Spill / Highway',
  'Wildland Fire (Rapid Spread)',
  'Vehicle Extrication (Pinned)',
  'Aircraft Crash (Airport)',
  'Train Derailment / Fire',
  'Confined Space Rescue',
  'High-Angle Rope Rescue',
  'Water Rescue (River/Flood)',
  'Electrical Substation Fire',
  'Arson in Progress',
  'Smoke Showing from Window',
  'Gas Main Rupture',
  'Transformer Explosion',
  'Fuel Tanker Fire',
  'Chimney Fire',
  'Forest Fire / Brush Fire',
  'Barn Fire (Livestock)',
  'Automatic Fire Alarm (Mall)',
  'Elevator Entrapment',
  'Vehicle Fire (Highway Shoulder)',
  'Electrical Panel Fire',
  'Carbon Monoxide Alarm',
  'Power Line Down / Arcing',
  'Dumpster Fire Near Structure',
  'Attic Fire (Smoldering)',
  'Kitchen Fire with Extension',
  'Wildland Fire (Wind Driven)',
  'Flood Rescue (Swift Water)',
  'Ice Rescue (Frozen Pond)',
  'Lightning Strike Fire',
  'Gas Meter Strike / Leak',
  'Storm Damage Check (Unstable Structure)',
  'Ice Storm Line Fire',
  'Boat Fire at Marina',
  'Wharf Building Fire',
  'Lighthouse Access Rescue',
  'Coastal Cliff Rope Rescue',
  'Storm Surge Water Rescue',
  'Ferry Terminal Fire Alarm',
  'Generator Fire (Extended Outage)',
  'Snow Load Roof Collapse Risk',
]

export const EMS_INCIDENT_TYPES = [
  // Legacy/compat names kept for existing logic/tests.
  'Cardiac arrest',
  'Unconscious person',
  'Mass Casualty Incident (MCI)',
  'Gunshot Wound (Critical)',
  'Stabbing Victim (Severe)',
  'Cardiac Arrest (CPR in Progress)',
  'Stroke / CVA Symptoms',
  'Overdose (Unconscious)',
  'Pedestrian Struck by Vehicle',
  'Major Trauma (Fall from Height)',
  'Anaphylactic Shock',
  'Severe Burn Victim',
  'Respiratory Distress (Cyanotic)',
  'Active Childbirth / Emergency',
  'Seizure in Progress',
  'Drowning / Submersion',
  'Electrocution (High Voltage)',
  'Attempted Suicide (Critical)',
  'Psychiatric Crisis (Violent)',
  'Allergic Reaction (Epi-Pen)',
  'Diabetic Emergency (Ketoacidosis)',
  'Internal Bleeding (Suspected)',
  'Poisoning / Ingestion',
  'Amputation (Accidental)',
  'Crush Injury (Industrial)',
  'Heatstroke (Unresponsive)',
  'Chest Pain / Cardiac Symptoms',
  'Difficulty Breathing (Asthma/COPD)',
  'Altered Mental Status',
  'Fall Injury (Head Strike)',
  'Motor Vehicle Crash (Injuries)',
  'Hypothermia / Cold Exposure',
  'Heat Exhaustion / Dehydration',
  'Near Drowning (Conscious)',
  'Opioid Overdose (Naloxone Needed)',
  'Behavioral Crisis (Medical Clearance)',
  'Carbon Monoxide Exposure',
  'Snowmobile / ATV Crash',
  'Floodwater Exposure Injury',
  'Electrocution (Downed Line)',
  'Fishing Vessel Dockside Injury',
  'Marina Slip-and-Fall (Hypothermia Risk)',
  'Storm Shelter Medical Assist',
  'Carbon Monoxide Exposure (Generator Use)',
  'Ferry Terminal Medical Emergency',
  'Ice-Related Fall (Harbor Walk)',
  'Cold-Water Immersion Rescue',
  'Severe Wind Debris Injury',
]

export const TOW_INCIDENT_TYPES = [
  // Legacy/compat names kept for existing logic/tests.
  'Flat tire change',
  'Vehicle extraction (ditch/snow)',
  'Multi-Vehicle Pileup Cleanup',
  'Jackknifed Semi-Truck',
  'Vehicle Overturned in Ditch',
  'Heavy Recovery (Bus/Truck)',
  'Police Impound (Felony)',
  'Abandoned Vehicle on Highway',
  'Disabled Vehicle (Travel Lane)',
  'Vehicle Recovery (Submerged)',
  'Roadway Obstruction (Debris)',
  'Post-Pursuit Pit Maneuver Tow',
  'Wrong-Way Driver Accident',
  'Flat Tire (Bridge/Tunnel)',
  'Dead Battery (Main Artery)',
  'Stolen Vehicle Recovery',
  'Parking Enforcement (Fire Lane)',
  'Unauthorized Parking (Private)',
  'Construction Site Recovery',
  'Wrecker Assist (Off-Road)',
  'Dead Battery Jump Start',
  'Vehicle Lockout Assistance',
  'Out of Fuel Roadside Assist',
  'Stuck Vehicle (Mud/Snow)',
  'Flood-Stalled Vehicle Recovery',
  'Icy Road Slide-Off Recovery',
  'Bridge Breakdown Tow',
  'Commercial Vehicle Breakdown',
  'Accident Scene Secondary Tow',
  'Illegally Parked Vehicle Removal',
  'Winch-Out (Embankment)',
  'Debris Strike Disabled Vehicle',
  'Severe Weather Pre-Position Tow',
  'Abandoned Vehicle (Snow Route)',
  'Causeway Breakdown Tow',
  'Ferry Queue Breakdown Assist',
  'Storm Surge Relocation Tow',
  'Salt Truck Assist Recovery',
  'Harbor Access Road Slide-Off',
  'Black Ice Multi-Car Tow',
  'Snowbank Entrapment Recovery',
  'Coastal Route Closure Tow Support',
]

export const PW_INCIDENT_TYPES = [
  'Fallen Tree (Road Blocked)',
  'Pothole Repair (Major Artery)',
  'Sinkhole Investigation',
  'Downed Power Lines (Secure Area)',
  'Flooded Intersection (Pump Required)',
  'Snow Removal (Emergency Route)',
  'Debris on Highway',
  'Broken Water Main',
  'Traffic Signal Outage (Temporary 4-Way)',
  'Sewer Backup / Overflow',
  'Street Sign Replacement (Missing STOP)',
  'Illegal Dumping (Hazmat Assessment)',
  'Bridge Structural Concern',
  'Graffiti Removal (City Property)',
  'Dead Animal Removal (Roadway)',
  'Streetlight Outage (Multiple)',
  'Black Ice Treatment (Bridge Deck)',
  'Flash Flood Barricade Setup',
  'Storm Drain Overflow Response',
  'Culvert Blockage / Debris',
  'Windstorm Debris Clearance',
  'Ice Control (Salt/Sand Deployment)',
  'Snow Drift Road Reopen',
  'Heat Buckled Asphalt Repair',
  'Mudslide / Washout Response',
  'Emergency Signage (Road Closed)',
  'Standing Water Pump-Out',
  'Tree Limb Hazard (Powerline Nearby)',
  'Storm Surge Barrier Deployment',
  'Coastal Road Overtopping Response',
  'Harbor Pump Station Overflow',
  'Breakwater Debris Clearance',
  'Dike Inspection (High Tide)',
  'Flash Freeze Brine Deployment',
  'Causeway Snow Drift Clearance',
  'Sea Spray Ice Control',
]

export const INCIDENT_TYPES_BY_DEPARTMENT = {
  police: CURATED_POLICE_INCIDENT_TYPES,
  fire: FIRE_INCIDENT_TYPES,
  ems: EMS_INCIDENT_TYPES,
  tow: TOW_INCIDENT_TYPES,
  public_works: PW_INCIDENT_TYPES,
}

export const INCIDENT_TYPES = Array.from(
  new Set(Object.values(INCIDENT_TYPES_BY_DEPARTMENT).flat())
)
